This adds additional error checking around MERLIN_TEST_OCAML_PATH

diff --git a/tests/merlin-wrapper b/tests/merlin-wrapper
--- a/tests/merlin-wrapper
+++ b/tests/merlin-wrapper
@@ -16,6 +16,12 @@ fi
 
 MERLIN_TEST_OCAMLLIB_PATH="$MERLIN_TEST_OCAML_PATH/lib/ocaml"
 
+if [ ! -d "$MERLIN_TEST_OCAMLLIB_PATH" ]; then
+    echo >&2 "Error: Directory $MERLIN_TEST_OCAMLLIB_PATH does not exist."
+    echo >&2 "Check that you've set MERLIN_TEST_OCAML_PATH correctly."
+    exit 1
+fi
+
 ocamlmerlin "$@" -ocamllib-path "$MERLIN_TEST_OCAMLLIB_PATH" \
     | jq 'del(.timing)' \
     | sed -e 's:"[^"]*lib/ocaml:"lib/ocaml:g' \
