Print useful info when git diff check fials

diff --git a/.github/workflows/flambda-backend.yml b/.github/workflows/flambda-backend.yml
--- a/.github/workflows/flambda-backend.yml
+++ b/.github/workflows/flambda-backend.yml
@@ -104,7 +104,12 @@ jobs:
         export MERLIN_TEST_OCAML_PATH=$GITHUB_WORKSPACE/flambda-backend/_install
         opam exec -- dune build
         opam exec -- dune runtest -p merlin-lib,dot-merlin-reader,merlin,ocaml-index
-        # Check if dune promoted any files. If this check fails, the likely culprit is
-        # that you compiled with the wrong menhir version. Cross-check your opam switch's
-        # menhir version with the one in merlin-lib.opam
-        git diff --quiet
+        if ! git diff --quiet ; then
+          echo "The following files were modified by dune:" >&2
+          git diff --name-only >&2
+          echo "" >&2
+          echo "Hint: If this check fails, the likely culprit is
+        that you compiled with the wrong menhir version. Cross-check your opam switch's
+        menhir version with the one in merlin-lib.opam" >&2
+          exit 1
+        fi
